openapi: 3.0.1
info:
  title: teacherAPI
  description: API Definition of teacherAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/teacher
paths:
  /getTeacher:
    get:
      responses:
        default:
          description: Default response
  /addTeacher:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
